packages:
  # Import the ld2450-base.yaml from local storage
  #ld2450_base: !include ld2450-base.yaml
  # Import the ld2450-base.yaml from github
  ld2450_base: github://everythingsmarthome/everything-presence-lite/common/ld2450-base.yaml@main
  
esphome:
  name: ld2450-02
  friendly_name: LD2450-02
 
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: "Y1CHUA9Gr1iT"

captive_portal:

web_server:
  version: 3
  port: 80

light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO04
    num_leds: 60
    name: "RGB LED"
